## Split keyboards
## https://zmk.dev/docs/config/system#split-keyboards
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

## Display Configuratoin
## https://zmk.dev/docs/config/displays
# CONFIG_ZMK_DISPLAY=n

# ## Track words per minute
# CONFIG_ZMK_WPM=y


## Input (needed for trackball split forwarding from peripheral)
CONFIG_INPUT=y

## Dongle Screen
CONFIG_DONGLE_SCREEN_BACKGROUND=y
CONFIG_DONGLE_SCREEN_KEYBOARD_STATUS=y
CONFIG_DONGLE_SCREEN_KEYBOARD_RGB_RIPPLE=n
CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n
CONFIG_DONGLE_SCREEN_TOGGLE_KEYCODE=113
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114
