## PMW3610 upstream Zephyr driver (Zephyr 4.1+)
CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_INPUT_PMW3610=y
CONFIG_ZMK_POINTING=y

CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n
CONFIG_DONGLE_SCREEN_TOGGLE_KEYCODE=113
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114
