# Uncomment the following line to enable deep sleep
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_TIMEOUT=30000
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

CONFIG_ZMK_EXT_POWER=n # see https://github.com/280Zo/charybdis-wireless-mini-zmk-firmware/issues/17
CONFIG_ZMK_BATTERY_REPORTING=y

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y

# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y

CONFIG_ZMK_WIDGET_WPM_STATUS=n

# CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
# CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

CONFIG_ZMK_KEYBOARD_NAME="Mini Charybdis"

# CONFIG_DONGLE_SCREEN_AMBIENT_LIGHT=n
# CONFIG_DONGLE_SCREEN_TOGGLE_KEYCODE=113
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=y
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_UP_KEYCODE=115
# CONFIG_DONGLE_SCREEN_BRIGHTNESS_DOWN_KEYCODE=114

CONFIG_ZMK_SPLIT=y
CONFIG_NRF_STORE_REBOOT_TYPE_GPREGRET=n
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y