manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    - name: tuanha168                            # <--- add this
      url-base: https://github.com/tuanha168     # <--- and this
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-config
      remote: mctechnology17
      revision: main
    - name: prospector-zmk-module                 # <--- and these
      remote: tuanha168                           # <---
      revision: main                              # <---
  self:
    path: config