manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: janpfischer
      url-base: https://github.com/janpfischer
    - name: 280Zo
      url-base: https://github.com/280Zo
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: abb64ba
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: janpfischer
      revision: main
    - name: zmk-pmw3610-driver
      remote: 280Zo
      revision: main
  self:
    path: config
